site_name: FrontISTR ver. 5.6
theme:
    name: 'material'
    highlightjs: true
    hljs_languages:
        - fortran
    language: 'en'

plugins:
  - search:

extra:
  search:
    language: 'en'

use_directory_urls: false

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - mdx_math
  - tables

extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - 'css/extra.css'

nav:
- HOME: index.md
- Introduction:
    - PDF: intro/intro_en.pdf
    - TOC: intro/index.md
    - Release Notes: intro/00_release_note.md
    - Cheat Sheet: intro/00_cheat_sheet.md
- Install:
    - PDF: install/install_en.pdf
    - TOC: install/index.md
    - Required software: install/install_01.md
    - Extracting the Archive File: install/install_02.md
    - Installation: install/install_03.md
    - Installation using cmake: install/install_04.md
    - Editing Makefile.conf: install/install_05.md
    - List of Makefile.conf Variables: install/install_06.md
    - Installation procedure to CentOS7.6(cmake): install/install_07.md
    - Installation procedure to CentOS7.6(Makefile.conf): install/install_08.md
    - Installation procedure to Ubuntu18.04(cmake): install/install_09.md
    - Installation procedure to Ubuntu18.04(Makefile.conf): install/install_10.md
    - Installation procedure to Windows10(Makefile.conf): install/install_11.md
- Theory:
    - TOC: theory/index.md
- Analysis:
    - TOC: analysis/index.md
    - Overall Control Data: analysis/analysis_03.md
    - Single Domeain Mesh Data: analysis/analysis_04.md
    - Analysis Control Data: analysis/analysis_05.md
- Tutorial:
    - TOC: tutorial/index.md
- FAQ: faq/index.md
