site_name: FrontISTR ver. 5.6
theme:
    name: 'material'
    highlightjs: true
    hljs_languages:
        - fortran
    language: 'ja'

plugins:
  - search:

extra:
  search:
    language: 'ja'

use_directory_urls: false

markdown_extensions:
    - attr_list
    - md_in_html
    - def_list
    - mdx_math
    - tables

extra_javascript:
    - 'javascripts/extra.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - 'css/extra.css'

nav:
- ホーム: index.md
- イントロダクション:
    - PDF: intro/intro_ja.pdf
    - 目次: intro/index.md
    - リリースノート: intro/00_release_note.md
    - チートシート(コマンド早見表): intro/00_cheat_sheet.md
- インストール:
    - PDF: install/install_ja.pdf
    - 目次: install/index.md
    - 動作環境: install/install_01.md
    - アーカイブの解凍・展開: install/install_02.md
    - インストールの概要: install/install_03.md
    - cmakeでのインストール: install/install_04.md
    - Makefile.confでのインストール: install/install_05.md
    - Makefile.confでの設定項目: install/install_06.md
    - CentOS7.6へのインストール手順例(cmake): install/install_07.md
    - Ubuntu18.04へのインストール手順例(cmake): install/install_09.md
    - CentOS7.6へのインストール手順例(Makefile.conf): install/install_08.md
    - Ubuntu18.04へのインストール手順例(Makefile.conf): install/install_10.md
    - Windows10へのインストール手順例(Makefile.conf): install/install_11.md
- 理論マニュアル:
    - 目次: theory/index.md
- 解析マニュアル:
    - 目次: analysis/index.md
    - 全体制御データ: analysis/analysis_03.md
    - 単一領域メッシュデータ: analysis/analysis_04.md
    - 解析制御データ: analysis/analysis_05.md
- チュートリアル:
    - 目次: tutorial/index.md
- FAQ: faq/index.md
